server:
  port: 1111
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: create
  application:
    name: coupon-service
eureka:
   client:
     register-with-eureka: true
     fetch-registry: false
     
     Service-url:
      defaultZone: http://localhost:8761/eureka   