server:
 port: 1111
spring:
 datasource:
    password: root
    url: jdbc:mysql://localhost:3306/javabatch
    username: root
 jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties: 
     hibernate: 
      format_sql: true
      
   
   
   
   
   