spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update
  application:
      name: product-service
  config:
    import:
    - optional:configserver:http://localhost:8888/ 
    
server:
 port: 1234
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
instance:
  prefer-ip-address: true
  
resilience4j:
  retry:
    instances:
      productionapi:
       max-attempts: 3
       wait-duration: 20s  